global using SQLite;
global using System.Collections.ObjectModel;
global using static Microsoft.Maui.Storage.FileSystem;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Farm.Model;
global using Farm.ViewModels;
global using Farm.Utility;
global using Farm.Views;
global using Microcharts;
global using Microcharts.Maui;
global using SkiaSharp;
